# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desginJogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 450)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 9, 631, 431))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(50, 100, 531, 91))
        self.label.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 36pt \"Showcard Gothic\";")
        self.label.setObjectName("label")
        self.btnJogar = QtWidgets.QPushButton(self.page_1)
        self.btnJogar.setGeometry(QtCore.QRect(250, 230, 121, 51))
        self.btnJogar.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 32pt \"Chiller\";")
        self.btnJogar.setObjectName("btnJogar")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.numJogadores = QtWidgets.QSpinBox(self.page_2)
        self.numJogadores.setGeometry(QtCore.QRect(260, 220, 131, 51))
        self.numJogadores.setStyleSheet("font: 24pt \"Chiller\";\n"
"color: rgb(170, 0, 0);")
        self.numJogadores.setObjectName("numJogadores")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(70, 150, 531, 51))
        self.label_3.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 32pt \"Chiller\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 531, 91))
        self.label_4.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 36pt \"Showcard Gothic\";")
        self.label_4.setObjectName("label_4")
        self.infoInicio = QtWidgets.QLabel(self.page_2)
        self.infoInicio.setGeometry(QtCore.QRect(6, 362, 611, 41))
        self.infoInicio.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 32pt \"Chiller\";")
        self.infoInicio.setText("")
        self.infoInicio.setObjectName("infoInicio")
        self.btnIniciar = QtWidgets.QPushButton(self.page_2)
        self.btnIniciar.setGeometry(QtCore.QRect(260, 290, 131, 51))
        self.btnIniciar.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 32pt \"Chiller\";")
        self.btnIniciar.setObjectName("btnIniciar")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(-4, 10, 631, 71))
        self.label_6.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 42pt \"Chiller\";")
        self.label_6.setObjectName("label_6")
        self.listaJogadores = QtWidgets.QListWidget(self.page_3)
        self.listaJogadores.setGeometry(QtCore.QRect(0, 90, 631, 341))
        self.listaJogadores.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 32pt \"Chiller\";")
        self.listaJogadores.setObjectName("listaJogadores")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.btnJogarDados = QtWidgets.QPushButton(self.page_4)
        self.btnJogarDados.setGeometry(QtCore.QRect(20, 320, 181, 41))
        self.btnJogarDados.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 24pt \"Chiller\";")
        self.btnJogarDados.setObjectName("btnJogarDados")
        self.btnFinalizerTurno = QtWidgets.QPushButton(self.page_4)
        self.btnFinalizerTurno.setGeometry(QtCore.QRect(220, 320, 181, 41))
        self.btnFinalizerTurno.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 24pt \"Chiller\";")
        self.btnFinalizerTurno.setObjectName("btnFinalizerTurno")
        self.infoJogadorAtual = QtWidgets.QListView(self.page_4)
        self.infoJogadorAtual.setGeometry(QtCore.QRect(410, 30, 211, 201))
        self.infoJogadorAtual.setObjectName("infoJogadorAtual")
        self.btnSair = QtWidgets.QPushButton(self.page_4)
        self.btnSair.setGeometry(QtCore.QRect(420, 320, 181, 41))
        self.btnSair.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 24pt \"Chiller\";")
        self.btnSair.setObjectName("btnSair")
        self.listaDados = QtWidgets.QLabel(self.page_4)
        self.listaDados.setGeometry(QtCore.QRect(20, 40, 361, 181))
        self.listaDados.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 24pt \"Chiller\";")
        self.listaDados.setText("")
        self.listaDados.setObjectName("listaDados")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZumbiDice"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ZUMBI DICE</p></body></html>"))
        self.btnJogar.setText(_translate("MainWindow", "Jogar"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Quantos jogadores vão jogar?</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ZUMBI DICE</p></body></html>"))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Lista Jogadores</p></body></html>"))
        self.btnJogarDados.setText(_translate("MainWindow", "Jogar Dados"))
        self.btnFinalizerTurno.setText(_translate("MainWindow", "Finalizar Turno"))
        self.btnSair.setText(_translate("MainWindow", "Sair"))
